/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jurls.examples.approximation;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author thorsten
 */
public class FunctionRenderer1D extends javax.swing.JPanel {

    public final List<RenderFunction1D> renderFunctions = new ArrayList<>();

    /**
     * Creates new form FunctionRenderer
     */
    public FunctionRenderer1D() {
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        g.setColor(Color.black);
        g.fillRect(0, 0, getWidth(), getHeight());

        for (RenderFunction1D rf : renderFunctions) {
            g.setColor(rf.getColor());

            double prevX = (double) 0;
            double prevY = (double) 0;
            for (double x = (double) 0; x < 1.0; x += 0.01) {
                double y0 =rf.compute(x);
                double y = (0.5 * y0+0.5)* (double) getHeight();
                int px = (int)((double) getWidth() * x);
                g.drawLine((int) prevX, (int) prevY, px, (int) y);
                prevX = (double) px;
                prevY = y;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void initComponents() {

        GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, (int) Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, (int) Short.MAX_VALUE)
        );
    }


    
    
}
